name: flutter_smart_course
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- State Management ---
  flutter_riverpod: ^2.5.1 # State management

  # --- Local Storage ---
  hive: ^2.2.3             # Core Hive database
  hive_flutter: ^1.1.0     # Flutter helpers for Hive

  # --- Navigation ---
  go_router: ^14.1.0       # Declarative routing

  # --- Utility & UI Enhancement Plugins ---
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1 # Efficient image loading
  flutter_animate: ^4.5.0      # Easy animations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # --- Code Generation for Hive ---
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true